//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Saludar", ReplyAction="http://tempuri.org/IService1/SaludarResponse")]
        string Saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Saludar", ReplyAction="http://tempuri.org/IService1/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suma", ReplyAction="http://tempuri.org/IService1/SumaResponse")]
        int Suma(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suma", ReplyAction="http://tempuri.org/IService1/SumaResponse")]
        System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Resta", ReplyAction="http://tempuri.org/IService1/RestaResponse")]
        int Resta(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Resta", ReplyAction="http://tempuri.org/IService1/RestaResponse")]
        System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Multipicacion", ReplyAction="http://tempuri.org/IService1/MultipicacionResponse")]
        int Multipicacion(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Multipicacion", ReplyAction="http://tempuri.org/IService1/MultipicacionResponse")]
        System.Threading.Tasks.Task<int> MultipicacionAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Division", ReplyAction="http://tempuri.org/IService1/DivisionResponse")]
        int Division(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Division", ReplyAction="http://tempuri.org/IService1/DivisionResponse")]
        System.Threading.Tasks.Task<int> DivisionAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PL.ServiceReference1.CompositeType GetDataUsingDataContract(PL.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PL.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PL.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PL.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PL.ServiceReference1.IService1>, PL.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludar(string nombre) {
            return base.Channel.Saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string nombre) {
            return base.Channel.SaludarAsync(nombre);
        }
        
        public int Suma(int Numero1, int Numero2) {
            return base.Channel.Suma(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2) {
            return base.Channel.SumaAsync(Numero1, Numero2);
        }
        
        public int Resta(int Numero1, int Numero2) {
            return base.Channel.Resta(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2) {
            return base.Channel.RestaAsync(Numero1, Numero2);
        }
        
        public int Multipicacion(int Numero1, int Numero2) {
            return base.Channel.Multipicacion(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> MultipicacionAsync(int Numero1, int Numero2) {
            return base.Channel.MultipicacionAsync(Numero1, Numero2);
        }
        
        public int Division(int Numero1, int Numero2) {
            return base.Channel.Division(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int Numero1, int Numero2) {
            return base.Channel.DivisionAsync(Numero1, Numero2);
        }
        
        public PL.ServiceReference1.CompositeType GetDataUsingDataContract(PL.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PL.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(PL.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
